# Copyright (c) 2014, the Dart project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

name: usage
version: 3.4.1
description: A Google Analytics wrapper for both command-line, web, and Flutter apps.
homepage: https://github.com/dart-lang/usage
author: Dart Team <misc@dartlang.org>

environment:
  sdk: '>=2.0.0-dev.30 <3.0.0'

dependencies:
  path: ^1.4.0

dev_dependencies:
  browser: ^0.10.0
  grinder: ^0.8.0
  test: ^0.12.0
